### PR TITLE
Cube Statistica Course Registrations' ML Model on Python

### PR DESCRIPTION
**Pull request by Abdullahsulehri10**
commiting to a new branch instead of main so people can review

### CODE REVIEW

**Review by FaizanKhalidMohsin — APPROVED** [review]
Good job!

**Comment by Abdullahsulehri10** [comment]
> 

Thank you so much sir! @FaizanKhalidMohsin

**Comment by Abdullahsulehri10** [comment]
Thank you so much sir!

**Comment by Abdullahsulehri10** [comment]
Thank you so much sir! @Faizan Khalid Mohsin

**Pull request merged**
